# Generated by Django 2.0 on 2020-04-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsapp', '0003_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='mobile',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='registration',
            name='pic',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
