# Generated by Django 2.0 on 2020-05-04 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsapp', '0004_auto_20200422_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'subscribe',
            },
        ),
    ]
