# Generated by Django 2.0 on 2020-05-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsapp', '0005_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('pic', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'facility',
            },
        ),
    ]
