# Generated by Django 2.0 on 2020-05-05 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsapp', '0006_facility'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('edate', models.CharField(max_length=200)),
                ('etime', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('pic', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'event',
            },
        ),
    ]
